# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cd9eeeceea28adf8bb34bd16114b7f65d3a2b89b9e45dadaf1a70294f9843aa775c4900172b0c0e9af18ebbde16fd9af6fbfc987bf0cc481b4252cb4b56fb19

test:
  secret_key_base: 85c6747876cee505559251854ae8dbb4d3afd6d518ddbe7458946b8078b9a3cd29fac6bc0b4638861f79ec5fa15546342a79dd8a781b26b7fad9bed2626270ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
